### ISSUE TITLE
Ways to access Evendim landscape and deeds

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#647]
Aable to go into evendim from the cliff goblin camp You are at: bx106 by115 c0 ox21.7223 oy26.0017 oz341.3 r89 (Instance 0)
Aable to progress evendim goblin slayer deed from the top of the goblin camp in Greenfields You are at: bx106 by115 c0 ox21.7223 oy26.0017 oz341.3 r89 (Instance 0)
Able to swim onto land and enter Evendim You are at: bx103 by124 c0 ox4.91923 oy56.4931 oz336.255 r241

**Comment by dawnz85** [comment]
The access from the river at 103,124 should be blocked by invisible walls. Needs testing.
The slayer deed is due to that part of the Shire camp being inside an Evendim block. Shouldn't be able to progress a level 35(?) deed on level 10 mobs. Special case required unfortunately, error in the original data.

**Comment by echoes-emu** [comment]
Blocking Evendim deeds is probably too much trouble for little benefit - we can decide to tackle this later if we want to
